### ISSUE TITLE
New Effects

### ISSUE THREAD

**Issue by RafaelZ49** [Dystortedd/Ult-Effects#2]
Just like you did the basic text effects, why not do the motion effects? For example: waving, shaking, flipping, iterating, skewing and growth... your code is well commented and you can understand how everything works even though I know almost nothing about shaders, I would really like to see how you would do these effects.
I really liked your shaders and it's a great tool for those who don't want to spend 25 or more dollars on a shader. Especially for those who don't live in a country that uses the dollar.

**Comment by Dystortedd** [comment]
yeah, but for some of them, it would require some hacky techniques to get the local position of the text, which is hard (very hard).
Will do, but in a month probably (school and stuff)

**Comment by RafaelZ49** [comment]
I understand, it's fair since this kind of thing is complicated to do. I eagerly await this kind of update :)

**Comment by Dystortedd** [comment]
Done ! added a lot of stuff which can be used to recreate the effects you mentioned. I will add some new ones with new updates, and I hope you enjoy :heart:
