### ISSUE TITLE
How to configure? [More detailed]

### ISSUE THREAD

**Issue by RafaelZ49** [Dystortedd/Ult-Effects#5]
Hello again, I would like you to explain or create an example for the leather effects, specifically for gradients and new textures because with just the pre-existing RGB effect it was a bit difficult to understand how to achieve the other effects, especially for me and others who don't understand anything about shaders...
Note: I'm loving your commitment to making shader effects accessible to everyone without having to pay $25 or more to get them. This pack allows me to create much more elaborate and visually beautiful assets, thank you very much.

**Comment by Dystortedd** [comment]
I will make a tutorial on how you can make your own effects in the future !
