### ISSUE TITLE
How can I use fullscreen and text position effects in version 1.20.4?

### ISSUE THREAD

**Issue by inrhor** [Dystortedd/Ult-Effects#7]
I’m working on a resource pack for version 1.20.4 and would like to know what parts need to be modified to enable fullscreen and text position effects. Could you please guide me on which files or settings I need to adjust to make these effects work in this version?

**Comment by Dystortedd** [comment]
Let me make this clear. The version currently supported is 1.21.3. I have no idea what should be changed in the shader files, as the shader itself was wrote in 1.21 when it first came out, so if you wanna make it work in 1.20.4, good luck
